#%RAML 0.8
---
title: Chef Server
version: 1
mediaType: application/json
documentation:
  - title: Chef Server API
    content:
      API for the Chef Server.

traits: !include common/traits.yml

/users: !include users.yml
/organizations: !include organizations.yml
